/*
 * generated by Xtext 2.12.0
 */
package rover.raspirover.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import rover.raspirover.xtext.parser.antlr.internal.InternalRaspiRoverParser;
import rover.raspirover.xtext.services.RaspiRoverGrammarAccess;

public class RaspiRoverParser extends AbstractAntlrParser {

	@Inject
	private RaspiRoverGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRaspiRoverParser createParser(XtextTokenStream stream) {
		return new InternalRaspiRoverParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Project";
	}

	public RaspiRoverGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RaspiRoverGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
