/*
 * generated by Xtext 2.12.0
 */
package rover.raspirover.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RaspiRoverStandaloneSetup extends RaspiRoverStandaloneSetupGenerated {

	def static void doSetup() {
		new RaspiRoverStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
