/*
 * generated by Xtext 2.12.0
 */
package rover.raspirover.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRaspiRoverScopeProvider extends DelegatingScopeProvider {
}
