/**
 * generated by Xtext 2.12.0
 */
package rover.raspirover.xtext.ide;

import rover.raspirover.xtext.ide.AbstractRaspiRoverIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RaspiRoverIdeModule extends AbstractRaspiRoverIdeModule {
}
