/**
 * generated by Xtext 2.12.0
 */
package rover.raspirover.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import rover.raspirover.xtext.RaspiRoverRuntimeModule;
import rover.raspirover.xtext.RaspiRoverStandaloneSetup;
import rover.raspirover.xtext.ide.RaspiRoverIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RaspiRoverIdeSetup extends RaspiRoverStandaloneSetup {
  @Override
  public Injector createInjector() {
    RaspiRoverRuntimeModule _raspiRoverRuntimeModule = new RaspiRoverRuntimeModule();
    RaspiRoverIdeModule _raspiRoverIdeModule = new RaspiRoverIdeModule();
    return Guice.createInjector(Modules2.mixin(_raspiRoverRuntimeModule, _raspiRoverIdeModule));
  }
}
