/**
 * generated by Xtext 2.12.0
 */
package rover.raspirover.xtext;

import rover.raspirover.xtext.AbstractRaspiRoverRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RaspiRoverRuntimeModule extends AbstractRaspiRoverRuntimeModule {
}
