/**
 * generated by Xtext 2.12.0
 */
package rover.raspirover.xtext;

import rover.raspirover.xtext.RaspiRoverStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RaspiRoverStandaloneSetup extends RaspiRoverStandaloneSetupGenerated {
  public static void doSetup() {
    new RaspiRoverStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
