/**
 * generated by Xtext 2.12.0
 */
package rover.raspirover.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import rover.raspirover.xtext.ui.AbstractRaspiRoverUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RaspiRoverUiModule extends AbstractRaspiRoverUiModule {
  public RaspiRoverUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
